spring:
  config:
    import: ./env/.env.dev[.properties]

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  flyway:
    enabled: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.springframework.security: DEBUG
  org.springframework.data.mongodb.core.MongoTemplate: DEBUG

springdoc:
  api-docs:
    version: openapi_3_0

  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

  swagger-ui:
    disable-swagger-default-url: true
    operations-sorter: alpha
    defaultModelsExpandDepth: -1
    tagsSorter: alpha
    operationsSorter: method

  cache:
    disabled: true

management:
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      base-path: "/api/actuator"
      exposure:
        include: "health"
    access:
      default: none
  endpoint:
    health:
      access: read-only
  health:
    ssl:
      enabled: false
