spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  output:
    ansi:
      enabled: always

  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_CLUSTER_URI}
      database: tekken

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

#springdoc:
#  swagger-ui:
#    disable-swagger-default-url: true
