INSERT INTO character
    (name, full_name, label, description)
values
    ('Kazuya', 'Kazuya Mishima', '카즈야', 'Cold-blooded Oppressor'),
    ('Jin', 'Jin Kazama', '진', 'lightning of fate'),
    ('King', 'King', '킹', 'Anger of the Beast'),
    ('Jun', 'Jun Kazama', '준', 'Light of Hope'),
    ('Paul', 'Paul Phoenix', '폴', 'Hot-blooded Destroyer'),
    ('Law', 'Marshall Law', '로우', 'The Legendary Dragon'),
    ('Jack-8', 'Jack-8', '잭8', 'High Tech Annihilator'),
    ('Lars', 'Lars Alexandersson', '라스', 'The Lion of the Rebellion'),
    ('Xiaoyu', 'Ling Xiaoyu', '샤오유', 'Dancing Phoenix'),
    ('Nina', 'Nina Williams', '니나', 'Silent Assassin'),
    ('Leroy', 'Leroy Smith', '리로이', 'Grandmaster of Drip'),
    ('Asuka', 'Asuka Kazama', '아스카', 'Spirited Peacemaker'),
    ('Lili', 'Lili', '리리', 'Fighting Heiress'),
    ('Bryan', 'Bryan Fury', '브라이언', 'Harbinger of Chaos'),
    ('Hwoarang', 'Hwoarang', '화랑', 'Blood Talon'),
    ('Claudio', 'Claudio Serafino', '클라우디오', 'Banisher of Demons'),
    ('Azucena', 'Azucena Milagros Ortiz Castillo', '아주세나', 'Perfect Blend'),
    ('Raven', 'Raven', '레이븐', 'Shadow Agent'),
    ('Leo', 'Leo', '레오', 'Seeker of Truth'),
    ('Steve', 'Steve', '스티브', 'Counter-punching Paragon'),
    ('Kuma', 'Kuma', '쿠마', 'Master of Salmon'),
    ('Yoshimitsu', 'Yoshimitsu', '요시미츠', 'Mechanized Space Ninja'),
    ('Shaheen', 'Shaheen', '샤힌', 'Desert Falcon'),
    ('Dragunov', 'Sergei Dragunov', '드라그노프', 'White Reaper'),
    ('Feng', 'Feng Wei', '펭', 'God Fist'),
    ('Panda', 'Panda', '판다', 'Pretty Protector'),
    ('Lee', 'Lee Chaolan', '리', 'Silver Haired Demon'),
    ('Alisa', 'Alisa Bosconovitch', '알리사', 'Destroying Automation'),
    ('Zafina', 'Zafina', '쟈피나', 'Mystic Stargazer'),
    ('Devil Jin', 'Devil Jin', '데빌 진', 'Black Wings of Ruin'),
    ('Victor', 'Victor Chevalier', '빅터', 'Refined Violence'),
    ('Reina', 'Reina', '레이나', 'Purple Lightning'),
    ('Eddy', 'Eddy Gordo', '에디', 'Indomitable Flash'),
    ('Lidia', 'Lidia', '리디아', 'The Warrior Prime Minister'),
    ('Heihachi', 'Heihachi Mishima', '헤이하치', 'Resurrected King of Iron Fist'),
    ('Clive', 'Clive Rosfield', '클라이브', 'Shield of the Undying Flame'),
    ('Anna', 'Anna Williams', '안나', 'Scarlet Lightning');
