INSERT INTO character
    (name, full_name, description)
values
    ('Kazuya', 'Kazuya Mishima', 'Cold-blooded Oppressor'),
    ('Jin',	'Jin Kazama', 'lightning of fate'),
    ('King', 'King', 'Anger of the Beast'),
    ('Jun', 'Jun Kazama', 'Light of Hope'),
    ('Paul', 'Paul Phoenix', 'Hot-blooded Destroyer'),
    ('Law',	'Marshall Law',	'The Legendary Dragon'),
    ('Jack-8', 'Jack-8', 'High Tech Annihilator'),
    ('Lars', 'Lars Alexandersson', 'The Lion of the Rebellion'),
    ('Xiaoyu', 'Ling Xiaoyu', 'Dancing Phoenix'),
    ('Nina', 'Nina Williams', 'Silent Assassin'),
    ('Leroy', 'Leroy Smith', 'Grandmaster of Drip'),
    ('Asuka', 'Asuka Kazama', 'Spirited Peacemaker'),
    ('Lili', 'Lili', 'Fighting Heiress'),
    ('Bryan', 'Bryan Fury',	'Harbinger of Chaos'),
    ('Hwoarang', 'Hwoarang', 'Blood Talon'),
    ('Claudio', 'Claudio Serafino', 'Banisher of Demons'),
    ('Azucena', 'Azucena Milagros Ortiz Castillo', 'Perfect Blend'),
    ('Raven', 'Raven', 'Shadow Agent'),
    ('Leo', 'Leo', 'Seeker of Truth'),
    ('Steve', 'Steve', 'Counter-punching Paragon'),
    ('Kuma', 'Kuma', 'Master of Salmon'),
    ('Yoshimitsu', 'Yoshimitsu', 'Mechanized Space Ninja'),
    ('Shaheen', 'Shaheen', 'Desert Falcon'),
    ('Dragunov', 'Sergei Dragunov', 'White Reaper'),
    ('Feng', 'Feng Wei', 'God Fist'),
    ('Panda', 'Panda', 'Pretty Protector'),
    ('Lee', 'Lee Chaolan', 'Silver Haired Demon'),
    ('Alisa', 'Alisa Bosconovitch',	'Destroying Automation'),
    ('Zafina', 'Zafina', 'Mystic Stargazer'),
    ('Devil Jin', 'Devil Jin', 'Black Wings of Ruin'),
    ('Victor', 'Victor Chevalier', 'Refined Violence'),
    ('Reina', 'Reina', 'Purple Lightning'),
    ('Eddy', 'Eddy Gordo', 'Indomitable Flash'),
    ('Lidia', 'Lidia', 'The Warrior Prime Minister'),
    ('Heihachi', 'Heihachi Mishima', 'Resurrected King of Iron Fist'),
    ('Clive', 'Clive Rosfield', 'Shield of the Undying Flame'),
    ('Anna', 'Anna Williams', 'Scarlet Lightning');